### ISSUE TITLE
Elasticity example with tying across both the boundaries

### ISSUE THREAD

**Issue by bhaveshshrimali** [jorgensd/dolfinx_mpc#2]
Hi @jorgensd ,
 
First off, thanks for the tool. I am trying to implement a simple linear elasticity example on a unit square with linear constraints tying dofs across both the sets of edges (namely left-right and top-bottom), but somehow I don't see the expected result. I modify the template provided in your elasticity example with:

   * Prescribing a `DirichletBC` $u_2 = 0$ on the bottom-right node (say node `P`)
   * Prescribing a `DirichletBC` $u_1 = 0$ on the top-left node  (say node `Q`)
   * Prescribing a `DirichletBC` $u = 0$ at the origin (0,0) (say node `o`)
   * Prescribing a `DirichletBC` $u_1 = 0.25$ on the bottom-right node (to stretch it uniaxially along x axis).

I then constrain the dofs on the left (`L`) - right (`R`) edges such that:

`u_R - u_L = u_P - u_o` for all nodes except the one at top-right corner `[1,1]`

and the

`u_T - u_B = u_Q - u_o` for all nodes except the one at top-right corner `[1,1]`

I expect to see something like the following (independently done using multi-point constraints in Abaqus). Note that the top corner isn't properly constrained (but I should expect the field to be reasonable elsewhere at least)

![trialUnitSquare](https://user-images.githubusercontent.com/22624037/80535179-01e9f200-8966-11ea-99ee-730fd29ec758.png)

Attached is the short snippet of the code (I want to avoid reposting the entire example just for brevity)

```python
V = VectorFunctionSpace(mesh, ("CG", 1)) 

Vx = V.sub(0).collapse()
Vy = V.sub(1).collapse()

# Define Dirichlet BC

zero = Function(V) 
zero_x = Function(Vx)
stretch_x = Function(Vx)
zero_y = Function(Vy)

with zero.vector.localForm() as zero_local:
    zero_local.set(0.0)
    
with zero_x.vector.localForm() as zero_local_x:
    zero_local_x.set(0.0)

with stretch_x.vector.localForm() as stretch_local_x:
    stretch_local_x.set(0.25)

with zero_y.vector.localForm() as zero_local_y:
    zero_local_y.set(0.0)

originDofs = locate_dofs_geometrical(V, lambda x: np.logical_and( np.isclose(x[0], 1.e-16),
                                                                  np.isclose(x[1], 1.e-16)))

botRightDofs_x = locate_dofs_geometrical((V.sub(0), Vx), lambda x: np.logical_and(np.isclose(x[0], 1.),
                                                                                  np.isclose(x[1], 0.)))

botRightDofs_y = locate_dofs_geometrical((V.sub(1), Vy), lambda x: np.logical_and(np.isclose(x[0], 1.),
                                                                                  np.isclose(x[1], 0.)))

topLeftDofs_x = locate_dofs_geometrical((V.sub(0), Vx), lambda x: np.logical_and(np.isclose(x[0], 0.),
                                                                                 np.isclose(x[1], 1.)))

topLeftDofs_y = locate_dofs_geometrical((V.sub(1), Vy), lambda x: np.logical_and(np.isclose(x[0], 0.),
                                                                                 np.isclose(x[1], 1.)))
# Applying Dirichlet BC's

bcOrigin =  DirichletBC(zero, originDofs)
rightStretch =  DirichletBC(stretch_x, botRightDofs_x, V.sub(0))
rightFixed =  DirichletBC(zero_y, botRightDofs_y, V.sub(1))
topFixed =  DirichletBC(zero_x, topLeftDofs_x, V.sub(0))

bcs = [bcOrigin, rightStretch, rightFixed, topFixed]

def slave_locater_x(i, N):
    return lambda x: dof_at(x, [1., float(i/N)])

def master_locater_x(i, N):
    return lambda x: dof_at(x, [0., float(i/N)])

def slave_locater_y(i, N):
    return lambda x: dof_at(x, [float(i/N), 1.])

def master_locater_y(i, N):
    return lambda x: dof_at(x, [float(i/N), 0.])

s_m_c = {}
# s_m_cY = {}  # to constrain the top node

# It is here that I believe the problem could be (although I am confident that I am constraining the dofs properly)
for i in range(1, N):
    s_m_c[slave_locater_x(i, N)] = {master_locater_x(i, N): 1.0,  lambda x: dof_at(x, [1., 0.]):1.0, lambda x: dof_at(x, [0., 0.]):-1.0}
    s_m_c[slave_locater_y(i, N)] = {master_locater_y(i, N): 1.0,  lambda x: dof_at(x, [0., 1.]):1.0, lambda x: dof_at(x, [0., 0.]):-1.0}

(slaves, masters, coeffs, offsets) = slave_master_structure(V, s_m_c)

mpc = MultiPointConstraint(V._cpp_object, slaves,
                            masters, coeffs, offsets)
```

However I am not getting displacements as expected.. Any ideas what could be going wrong ? 
This is the entire file, in case if you want to run it: 

[dolfinx_mpc_elasticity_periodic.zip](https://github.com/jorgensd/dolfinx_mpc/files/4548356/dolfinx_mpc_elasticity_periodic.zip)

These are the results I get from the above modified code: 

![u1](https://user-images.githubusercontent.com/22624037/80536188-9ef95a80-8967-11ea-8119-c30bb3024d10.png)

![u2](https://user-images.githubusercontent.com/22624037/80536206-a3be0e80-8967-11ea-8bf1-6552a705c178.png)

**Comment by jorgensd** [comment]
The tool does not support tying strong Dirichlet boundary conditions with multipoint constraints. 
It might do in the future, but it requires a careful design. However, if you enforce your dirichlet boundary conditions weakly, by using for instance Nitsche's method and the `ds` measure, you should be able to couple the degrees of freedom together.

**Comment by bhaveshshrimali** [comment]
I see. Thanks for your quick reply.
Will try imposing the Dirichlet BC's weakly.

**Comment by bhaveshshrimali** [comment]
I am working on adding the Nitsche terms for weakly imposing the Dirichlet BCs. However, I just wanted to be sure that the formulation would indeed work for (nearly) incompressible materials (`lmbda = + inf`). Does `ffcx` support the non-conforming Crouziex-Raviart elements (`CR`)? 

In particular, I observed that setting 
```python
V = VectorFunctionSpace(mesh, ("CR", 1)) 
```
returns an empty `slave_master_structure`

**Comment by jorgensd** [comment]
> I am working on adding the Nitsche terms for weakly imposing the Dirichlet BCs. However, I just wanted to be sure that the formulation would indeed work for (nearly) incompressible materials (`lmbda = + inf`). Does `ffcx` support the non-conforming Crouziex-Raviart elements (`CR`)?
> 
> In particular, I observed that setting
> 
> ```python
> V = VectorFunctionSpace(mesh, ("CR", 1)) 
> ```
> 
> returns an empty `slave_master_structure`

As far as I am aware of, ffcx supports all elements on simplex domains (triangles and tetrahedrons).
I will look into why slave_master_structure is empty for CR elements.
