### ISSUE TITLE
create_periodic_constraint_topological() produces unusual sparsity patterns

### ISSUE THREAD

**Issue by fmonteghetti** [jorgensd/dolfinx_mpc#20]
Hi Jørgen,

This may not be a bug, but I think it is worth reporting since the behavior is significantly different from that of fenics.

**Issue:** `create_periodic_constraint_topological()` produces sparsity patterns that suggest that too many nodes are influenced by the periodic boundaries.

**Reproduction steps:** Run the attached demo_periodic_gep.py in dokken92/dolfinx_mpc:v0.4.1 and compare A_obtained_with_dolfinx_mpc.png to A_obtained_with_fenics.png.

**Background:** Even though the periodic boundary condition has only 49 slave nodes, the sparsity pattern of A shows that all the nodes are affected by the periodic boundary condition. By contrast, fenics does produce the expected pattern (A_obtained_with_fenics.png). 

**Attachment:** [issue-sparsity-pattern.zip](https://github.com/jorgensd/dolfinx_mpc/files/9267365/issue-sparsity-pattern.zip)
	- demo_periodic_gep.py: identical to the demo available in dokken92/dolfinx_mpc:v0.4.1 with added lines to export the sparsity pattern.
	- A_obtained_with_dolfinx_mpc.png: sparsity pattern of A obtained by running demo_periodic_gep.py in dokken92/dolfinx_mpc:v0.4.1.
	- A_obtained_with_fenics.png: sparsity pattern of A obtained with fenics for the same problem.

**Comment by jorgensd** [comment]
The implementation of periodic conditions in DOLFINx and DOLFIN is completely different.

In DOLFIN, one has to assume that a single dof is connected to only one other degree of freedom, i.e. non-matching sides cannot map to eachother. This means that you can reduce the size of the dofmap by replacing the degree of freedom that should be constrained with the one on the other side.

In DOLFINx, the assumption is more general, you can have non-conforming interfaces with a periodic mapping.
However, this means that the contraints for different degrees of freedom can interact. See: https://fenics2021.com/talks/dokken.html slides 4-6. This means that the MPC has a significant increase of entries in the sparisty pattern, to account for these potential contributions.
