### ISSUE TITLE
Error in the periodic boundary condition in the parallel case

### ISSUE THREAD

**Issue by Alchem334** [jorgensd/dolfinx_mpc#28]
Greetings to everyone!

I found a bug in the periodic boundary condition. The error occurs only in the parallel case.

Here is a simple test case on which an error occurs https://gist.github.com/Alchem334/3c871adca89573d411c1da56988d84e2

The transient Laplace equation is solved on a 2D square grid. Non-uniform initial data are given. In the lower left corner the function is equal to 1, in the rest of the region it is equal to 0. On the faces of the square x = 0 and x = 1, a periodic boundary condition is set.

On one core, a plausible result is obtained. 

![1_core](https://user-images.githubusercontent.com/75152535/199917611-6e97b47f-264c-46a1-85cf-7769f9272bc7.png)

On three cores, it is noticeable that the periodic condition is not satisfied.

![3_cores](https://user-images.githubusercontent.com/75152535/199917702-d9c57ec3-5a91-4e5c-8f00-40bc7c419f7f.png)

This error occurs due to the MPI call to MPI_Neighbor_alltoallv

https://github.com/jorgensd/dolfinx_mpc/blob/f7809a69699c4aaf2f602ed097a1ed4cf36e5968/cpp/utils.h#L235-L240

The vectors num_remote_slaves, remote_slave_disp_out, num_incoming_slaves, slave_disp_in can be empty on some cores in the parallel case, which causes the MPI call to silently throw error 13 MPI_ERR_UNKNOWN. 

Here is the error workaround

```
  std::vector<int> num_remote_slaves_new = num_remote_slaves;
  std::vector<int> remote_slave_disp_out_new = remote_slave_disp_out;
  std::vector<int> slave_disp_in_new = slave_disp_in;
  std::vector<int> num_incoming_slaves_new = num_incoming_slaves;

  if(num_remote_slaves_new.size()==0) num_remote_slaves_new.resize(1);
  if(remote_slave_disp_out_new.size()==0) remote_slave_disp_out_new.resize(1);
  if(slave_disp_in_new.size()==0) slave_disp_in_new.resize(1);
  if(num_incoming_slaves_new.size()==0) num_incoming_slaves_new.resize(1);

  MPI_Neighbor_alltoallv(
      num_masters_per_slave.data(), num_remote_slaves_new.data(),
      remote_slave_disp_out_new.data(), dolfinx::MPI::mpi_type<std::int32_t>(),
      recv_num_masters_per_slave.data(), num_incoming_slaves_new.data(),
      slave_disp_in_new.data(), dolfinx::MPI::mpi_type<std::int32_t>(),
      master_to_slave);
```

I'm not sure if this kind of error occurs on any version of OpenMPI. The bug was found on OpenMPI-3.1.3

**Comment by jorgensd** [comment]
Thanks for a very detailed description of your problem.
I cannot reproduce this using `OpenMPI-4.1.4`, see the attached Dockerfile for the setup of this:
```docker
FROM fenicsproject/test-env:v0.5.1-openmpi

ENV PETSC_ARCH="linux-gnu-real-32"
ARG FFCX=v0.5.0.post0
ARG BASIX=v0.5.1
ARG UFL=2022.2.0
ARG DOLFINX=v0.5.1
ARG MPC=v0.5.0.post0

WORKDIR /tmp

# Clone repos
RUN git clone --single-branch --branch=${BASIX} https://github.com/FEniCS/basix.git
RUN git clone --single-branch --branch=${DOLFINX} https://github.com/FEniCS/dolfinx.git
RUN git clone --single-branch --branch=${MPC} https://github.com/jorgensd/dolfinx_mpc.git


# Install basix
RUN cmake -G Ninja -B build-basix -DCMAKE_BUILD_TYPE="Release" -S ./basix/cpp/ && \
    cmake --build build-basix --parallel 3 && \
    cmake --install build-basix && \
    BUILD_TYPE="Release" pip3 install ./basix/python

# Install ufl
RUN python3 -m pip install git+https://github.com/FEniCS/ufl.git@${UFL}
# Install ffcx
RUN python3 -m pip install git+https://github.com/FEniCS/ffcx.git@${FFCX}

# Install DOLFINx
RUN cmake -G Ninja -DCMAKE_BUILD_TYPE="Release" -B build-dolfinx -S ./dolfinx/cpp/ && \
    cmake --build build-dolfinx && \
    cmake --install build-dolfinx && \
    BUILD_TYPE="Release" python3 -m pip -v install ./dolfinx/python/

# Install DOLFINx_mpc
RUN cmake -G Ninja -B build-dir -DCMAKE_BUILD_TYPE="Debug" -S ./dolfinx_mpc/cpp/ && \
    cmake --build build-dir --parallel 3 && \
    cmake --install build-dir && \
    python3 -m pip -v install ./dolfinx_mpc/python/

ENV OMPI_ALLOW_RUN_AS_ROOT=1
ENV OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
```
```bash
root@dokken-XPS-9320:~/shared# mpirun --version
mpirun (Open MPI) 4.1.4

Report bugs to http://www.open-mpi.org/community/help/
root@dokken-XPS-9320:~/shared# mpirun -n 3 python3 mwe_old.py 
```

If you want to put in a Pull Request with a fix, Im happy with that.

Could you trying adapting the following syntax in favor of the one above:
```c++
if (num_remote_slaves_new.empty())
    num_remote_slaves.reserve(1)
```

**Comment by jorgensd** [comment]
I believe this issue has been resolved. Please re-open if still applicable.
