### ISSUE TITLE
Imposition of periodic constraints  with geometrical dof location

### ISSUE THREAD

**Issue by bleyerj** [jorgensd/dolfinx_mpc#4]
Currently, `create_periodic_constraint` uses `locate_dofs_topological`. It might be interesting to provide a similar functionality with `locate_dofs_geometrical`. This would enable to support periodic boundary conditions on DG elements.

I can propose a PR for this. @jorgensd  would you be OK in changing the API to two `create_periodic_constraint_geometrical` and `create_periodic_constraint_topological` methods instead of `create_periodic_constraint` ? Or do you prefer a single `create_periodic_constraint` with a `method="topological"/"geometrical"` optional keyword ?

**Comment by jorgensd** [comment]
I'll think about it today. I need to have a closer look at periodic constraint and see if I can make it into some modules (for less code duplication).

**Comment by jorgensd** [comment]
@bleyerj I've made a branch with the suggested changes: 
https://github.com/jorgensd/dolfinx_mpc/compare/dokken/periodic_geometrical

Do you have any additional input on it? I'll merge it once CI passes

**Comment by bleyerj** [comment]
sounds perfect to me. Thanks

**Comment by jorgensd** [comment]
Resolved in: https://github.com/jorgensd/dolfinx_mpc/commit/920a0d53d2c08a04580a8d356d7e9d16c32205d3
