### ISSUE TITLE
Periodic condition on mixed space

### ISSUE THREAD

**Issue by Alchem334** [jorgensd/dolfinx_mpc#6]
Dolfin-x commit https://github.com/FEniCS/dolfinx/commit/d05ae91d21af3ecb0bb704aefc8dc2256dbfb040

dolfinx_mpc commit 25543be69ec1dd3c9bb0f14770d9c121c306252e

I don't know how to implement a periodic boundary condition on a mixed function space. I am attaching the code that solves the Cahn-Hilliard equation on a 2D computational domain. 

https://gist.github.com/Alchem334/5bfab723af41ff32130b049fb5b0c51c

An attempt to implement the boundary condition as in the examples "demo_periodic3d_topological" and "demo_periodic_geometrical" leads to a segmentation fault in the https://github.com/jorgensd/dolfinx_mpc/blob/25543be69ec1dd3c9bb0f14770d9c121c306252e/python/dolfinx_mpc/periodic_condition.py#L34-L36 function.

Segmentation fault occurs on the code line https://github.com/jorgensd/dolfinx_mpc/blob/25543be69ec1dd3c9bb0f14770d9c121c306252e/python/dolfinx_mpc/periodic_condition.py#L48
because apparently the "tabulate_dof_coordinates" function does not work with mixed space. Is there some way to get around this problem?

**Comment by jorgensd** [comment]
I'm currently working on this in the branch https://github.com/jorgensd/dolfinx_mpc/tree/dokken/periodic-sub

**Comment by jorgensd** [comment]
Fixed in: https://github.com/jorgensd/dolfinx_mpc/commit/29864aad71e57f0d1faeb3cbefb22d225f94a503
