### ISSUE TITLE
Missing <algorithm> in assemble_utils.cpp

### ISSUE THREAD

**Issue by LucasPa** [jorgensd/dolfinx_mpc#80]
Hi,

When running `ninja -j3 install -C build-dir`, the following error was raised:

```
dolfinx_mpc/cpp/assemble_utils.cpp:22:24: error: ‘find’ is not a member of ‘std’
```
I fixed that by adding `#include <algorithm>` in that file. Am I the only one who needed to add this `include`? Maybe it would be worth adding it for everyone.

Best,

Lucas

**Comment by drew-parsons** [comment]
Affects debian builds too.

**Comment by jorgensd** [comment]
Ok, Lets add it in (i Guess i Need some post releases)

**Comment by jorgensd** [comment]
Post release has been added (v0.7.0.post0) with the fix included
