### ISSUE TITLE
Error with Compiling on Mac M1 

### ISSUE THREAD

**Issue by jorgenin** [jorgensd/dolfinx_mpc#88]
Hi I'm trying to compile MPC for a Mac M1 with dolfinx 0.7.0.
It seems like I'm getting a few issues with the compilation. 

The first issue is the following: 
<img width="1103" alt="Screenshot 2023-10-30 at 11 02 31 PM" src="https://github.com/jorgensd/dolfinx_mpc/assets/93843698/2bb15590-de0e-4117-a1a0-80ff7f5673d6">

I changed then the import headers from: 
<img width="288" alt="Screenshot 2023-10-30 at 11 00 28 PM" src="https://github.com/jorgensd/dolfinx_mpc/assets/93843698/a6fd609f-f8d1-437f-ab83-fc76f0dca338">

To: 
<img width="361" alt="Screenshot 2023-10-30 at 11 03 24 PM" src="https://github.com/jorgensd/dolfinx_mpc/assets/93843698/acd3eca6-1309-4435-a9b4-db2a199c0c53">

But then I get a new issue: 
<img width="962" alt="Screenshot 2023-10-30 at 11 04 24 PM" src="https://github.com/jorgensd/dolfinx_mpc/assets/93843698/e23924a5-e78e-4294-8ffc-2be79511c953">

I'm thinking that because of the above issues I'm just having a problem with the exact imports / files I have. I was wondering if there were any suggestions on how to fix this.

Best,
Jorge

**Comment by jorgensd** [comment]
How did you install dolfinx?

**Comment by jorgenin** [comment]
I installed it by compiling from source. I'm using the 0.7.0 post 0

**Comment by jorgensd** [comment]
> I installed it by compiling from source. I'm using the 0.7.0 post 0

Could you add your exact commands for building dolfinx here, then I will see if I can recreate it (i dont have a Mac, so a bit tricky to test).

**Comment by jorgenin** [comment]
Thanks a lot for the help: 

so right now I'm doing: 
cmake -DCMAKE_INSTALL_PREFIX=/usr/local/dolfinx_real ../
then:
make
then:
make install

Lastly I pip install the dolfinx python into

/usr/local/dolfinx_real/lib/python3.11/dist-packages

**Comment by jorgenin** [comment]
I then add that directory to the Python path (when I'm using dolfinx) so far it's worked out great. I can run dolfinx and haven't had any issues with it. 
I also wanted to clarify. I'm not having issues with the initial library compile of MPC:

cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -B build-dir cpp/
ninja -j3 install -C build-dir

These two commands seem to work fine and install.

It's just the final command :

python3 -m pip install python/. --upgrade

Which breaks things. 
I've tried just running cmake --build in the python folder to try to debug it but it still has similar issues.

**Comment by jorgensd** [comment]
Close as conda builds should work for later releases on MAC M1. Please reopen if this is still an issue.
