### ISSUE TITLE
Unable to run demo_periodic3d_topological.py out-of-the-box

### ISSUE THREAD

**Issue by adityasatyadeep** [jorgensd/dolfinx_mpc#90]
Hi, I was trying to use dolfinx to implement periodic boundary conditions and came across the dolfinx_mpc package. 
However, when I try to run the demo_periodic3d_topological.py example, I run into numerous errors, like default_scalar_type cannot be imported from dolfinx and the default parameters passed into create_periodic_constraint_topological() don't seem to be correct. I suspect the demo is out-of-date; is there a more updated demo that I can take a look at? 
For reference, I'm running Python 3.9.9, dolfinx 0.6.0, and dolfinx_mpc 0.6.1.

**Comment by jorgensd** [comment]
How did you download the demo?
There are branches for the demos of each release:
v0.7.0: https://github.com/jorgensd/dolfinx_mpc/blob/v0.7.0.post1/python/demos/demo_periodic3d_topological.py
v0.6.0: https://github.com/jorgensd/dolfinx_mpc/blob/v0.6.1.post1/python/demos/demo_periodic3d_topological.py

To me it seems like you are trying to use the main branch, which is aiming to be up to date with DOLFINx main.

**Comment by jorgensd** [comment]
@astrotheory6 did you resolve your issue?

**Comment by jorgensd** [comment]
Closing due to no feedback.
